# Pre-commit
# https://pre-commit.com/#usage

default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.5.0"
  hooks:
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: name-tests-test
    args:
      - --django
  - id: trailing-whitespace
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: "v9.11.0"
  hooks:
  - id: commitlint
    stages:
    - commit-msg
    additional_dependencies:
    - "@commitlint/config-conventional"
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: "v0.11.0"
  hooks:
  - id: markdownlint-cli2
    files: (docs)
- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.6"
  hooks:
  - id: codespell
    additional_dependencies: [tomli]
- repo: https://github.com/python-poetry/poetry
  rev: "1.7.0"
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-install
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.1.11"
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
  - id: ruff-format
- repo: local
  hooks:
  - id: django-check
    name: django-check
    entry:
      poetry run python manage.py check
    language: system
    pass_filenames: false
  - id: django-makemigrations
    name: django-makemigrations
    entry:
      poetry run python manage.py makemigrations --check --dry-run
    language: system
    pass_filenames: false

# Pre-commit.ci
# https://pre-commit.ci/#configuration

ci:
  autofix_commit_msg:
    "fix: resolve issues raised by Pre-commit hooks"
  autoupdate_commit_msg:
    "chore(pre-commit.ci): bump hook versions"
  skip:
  - poetry-check
  - poetry-lock
  - poetry-install
  - django-check
  - django-makemigrations
