name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4.1.1
    - name: Cache Poetry
      id: cache-poetry
      uses: actions/cache@v3.3.2
      with:
        path: ~/.local
        key: poetry
    - name: Install Poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1.3.4
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        cache: poetry
    - name: Install dependencies
      run:
        poetry install --no-root --only=lint
    - name: Run formatter
      run:
        poetry run ruff format .
    - name: Run linter
      run:
        poetry run ruff .
